### ISSUE TITLE
KeyError: 'mean_gc'

### ISSUE THREAD

**Issue by snayfach** [bobeobibo/phigaro#23]
Error running version phigaro 2.2.4-1:

```
$ phigaro -c config.yml -f test.fna -o out/${SLURM_ARRAY_TASK_ID} --not-open -e tsv -d
Traceback (most recent call last):
  File "/global/home/users/snayfach/.conda/envs/phigaro_env/bin/phigaro", line 8, in <module>
    sys.exit(main())
  File "/global/home/users/snayfach/.conda/envs/phigaro_env/lib/python3.7/site-packages/phigaro/cli/batch.py", line 210, in main
    task_output_file = run_tasks_chain(tasks)
  File "/global/home/users/snayfach/.conda/envs/phigaro_env/lib/python3.7/site-packages/phigaro/batch/runner.py", line 20, in run_tasks_chain
    task.run()
  File "/global/home/users/snayfach/.conda/envs/phigaro_env/lib/python3.7/site-packages/phigaro/batch/task/run_phigaro.py", line 69, in run
    mean_gc = self.config['phigaro']['mean_gc']
KeyError: 'mean_gc'
```

**Comment by PollyTikhonova** [comment]
Hello, your problems (this and previous) will be solved if you use the given file:
https://github.com/bobeobibo/phigaro/blob/master/config.yml

I am sorry, I forgot to update this part of READ.me while updating Phigaro up to 2.x.x version, I correct it now.

And thank you for the interest in our tool!)
