### ISSUE TITLE
Wrong paths are used when installing figaro via conda

### ISSUE THREAD

**Issue by kabilov** [bobeobibo/phigaro#39]
Dear colleagues,

I installed phigaro via conda, creating a separate environment (phigaro). But the software does not work, because it accesses programs using the wrong path.

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/phigaro/bin/phigaro", line 10, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/phigaro/lib/python3.6/site-packages/phigaro/cli/batch.py", line 232, in main
    substitutions, ProdigalTask, preprocess_task=preprocess_task
  File "/home/user/anaconda3/envs/phigaro/lib/python3.6/site-packages/phigaro/cli/batch.py", line 35, in create_task
    task = task_class(*args, **kwargs)
  File "/home/user/anaconda3/envs/phigaro/lib/python3.6/site-packages/phigaro/batch/task/prodigal.py", line 14, in __init__
    self.prodigal = sh.Command(self.config['prodigal']['bin']).bake(
  File "/home/user/anaconda3/envs/phigaro/lib/python3.6/site-packages/sh.py", line 788, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: /home/user/anaconda3/bin/prodigal

But path must be /home/kabilov/anaconda3/envs/phigaro/bin/prodigal

**Comment by PollyTikhonova** [comment]
I believe an option of manual providing the paths/config file would solve the issue.
